// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Campus struct {
	CampusID    string       `json:"campusID"`
	Name        string       `json:"name"`
	City        string       `json:"city"`
	Bounds      *MapBounds   `json:"bounds"`
	ActivePilot *PilotStatus `json:"activePilot,omitempty"`
}

type LiveLocation struct {
	PilotID   string  `json:"pilotId"`
	CampusID  string  `json:"campusID"`
	Lat       float64 `json:"lat"`
	Lng       float64 `json:"lng"`
	Bearing   float64 `json:"bearing"`
	SpeedKmh  float64 `json:"speedKmh"`
	UpdatedAt string  `json:"updatedAt"`
}

type MapBounds struct {
	SwLat float64  `json:"swLat"`
	SwLng float64  `json:"swLng"`
	NeLat *float64 `json:"neLat,omitempty"`
	NeLng float64  `json:"neLng"`
}

type PilotStatus struct {
	PilotID  string `json:"pilotId"`
	FullName string `json:"fullName"`
	IsOnline bool   `json:"isOnline"`
	LastSeen string `json:"lastSeen"`
}

type Query struct {
}
