package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"

	"github.com/umg-bus-app/backend/graph/model"
)

// ChangeCampus is the resolver for the changeCampus field.
func (r *mutationResolver) ChangeCampus(ctx context.Context, studentID string, toCampusID string) (bool, error) {
	if _, err := r.CampusRepo.GetByID(ctx, toCampusID); err != nil {
		return false, fmt.Errorf("campus destino no existe")

	}
	if err := r.StudentRepo.ChangeCampus(ctx, studentID, toCampusID); err != nil {
		return false, err
	}

	return true, nil
}

// Campuses is the resolver for the campuses field.
func (r *queryResolver) Campuses(ctx context.Context) ([]*model.Campus, error) {
	campuses, err := r.CampusRepo.GetAll(ctx)
	if err != nil {
		return nil, err
	}
	var result []*model.Campus
	for _, c := range campuses {
		campus := &model.Campus{
			CampusID: c.CampusID.String(),
			Name:     c.Name,
			City:     c.City,
			Bounds: &model.MapBounds{
				SwLat: c.BoundSWLat,
				SwLng: c.BoundSWLng,
				NeLat: &c.BoundNELat,
				NeLng: c.BoundNELng,
			},
		}
		result = append(result, campus)
	}
	return result, nil
}

// Campus is the resolver for the campus field.
func (r *queryResolver) Campus(ctx context.Context, id string) (*model.Campus, error) {
	c, err := r.CampusRepo.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("Campus no encontrado.")

	}
	return &model.Campus{
		CampusID: c.CampusID.String(),
		Name:     c.Name,
		City:     c.City,
		Bounds: &model.MapBounds{
			SwLat: c.BoundSWLat,
			SwLng: c.BoundSWLng,
			NeLat: &c.BoundNELat,
			NeLng: c.BoundNELng,
		},
	}, nil
}

// LiveLocation is the resolver for the liveLocation field.
func (r *queryResolver) LiveLocation(ctx context.Context, campusID string) (*model.LiveLocation, error) {
	loc, err := r.Hub.GetLiveLocation(ctx, campusID)
	if err != nil {
		return nil, fmt.Errorf("sin ubicacion activa para el campus: %w", err)
	}

	return &model.LiveLocation{
		PilotID:   loc.PilotoID,
		CampusID:  loc.CampusID,
		Lat:       loc.Lat,
		Lng:       loc.Lng,
		Bearing:   loc.Bearing,
		SpeedKmh:  loc.Speed,
		UpdatedAt: loc.UpdatedAt.String(),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
